name: Trigger Sync

on:
  repository_dispatch:
    types: [sync_image]

jobs:
  deploy-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: "https://${{ secrets.ACR_SERVER }}"
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - env:
          REGISTRY: ${{ github.event.client_payload.registry }}
          NAMESPACE: ${{ github.event.client_payload.namespace }}
          NAME: ${{ github.event.client_payload.name }}
          TOREGISTRY: "${{ secrets.ACR_SERVER }}"
        run: 
          bash ./sync.sh $REGISTRY $NAMESPACE $NAME $TOREGISTRY
